### ISSUE TITLE
GTK warnings

### ISSUE THREAD

**Issue by oulenz** [loopbio/opencv-feedstock#4]
I installed with `conda install -c loopbio -c conda-forge -c pkgw-forge ffmpeg-feature ffmpeg gtk2 opencv-turbo` as discussed in [this thread](https://github.com/conda-forge/opencv-feedstock/issues/43). Ubuntu 16.10, Python 3.5.3. When running a simple program that uses `imshow`, I  receive the following warnings, although the program otherwise runs fine:

```
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "atk-bridge"

(71:17681): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
```

**Comment by sdvillal** [comment]
Yes, these messages are annoying, but as you say, they are not a big problem. They would most probably happen also if you were compiling against your system's GTK - I think they are due to misconfiguration in systems with GTK2 + GTK3.

What I do in my system is to unset GTK_MODULES, and that removes the warnings. For example, in your ```.bashrc``` or before your command:
```
GTK_MODULES=""
 ```

I do not have a reference for this but it should not be hard to google.

**Comment by oulenz** [comment]
If the warnings are innocent, I am not bothered by them. I am very grateful that you decided to go ahead and make available a build with GTK2 for linux, rather than wait for when you had a fix for Windows and Mac as well.

**Comment by kmario23** [comment]
@sdvillal Even with setting `GTK_MODULES=""` I'm still facing one more warning

`Gtk-Message: Failed to load module "canberra-gtk-module"`

Any thoughts about how to silence these as well please?

**Comment by sdvillal** [comment]
Unsetting GTK_MODULES makes the trick for me, also for the canberra module. I'm afraid I cannot help beyond that, and I think this is a system configuration issue and not a problem with the package.
