### ISSUE TITLE
Reading and writing videos via opencv does not work on linux

### ISSUE THREAD

**Issue by sdvillal** [loopbio/opencv-feedstock#6]
Upstream issue: https://github.com/conda-forge/opencv-feedstock/issues/73

The solution, package v4l and v4l-utils into conda-forge. Do time allowing.

Unfortunately it is not only that it does not work, it does not work silently. So in the meantime, we should add strong checks of this happening (for example, check that a video file is being created).

**Comment by sdvillal** [comment]
Apparently the problem was an unfortunate combination of an [opencv 3.2.0 issue](https://github.com/opencv/opencv/issues/8097) ([fixed in master](https://github.com/opencv/opencv/pull/8561)), building with an old version of gcc (the price to pay when you want stuff to work almost anywhere) and tests that were not running. It probably will get solved when [this PR](https://github.com/conda-forge/opencv-feedstock/pull/75) gets merged upstream. I keep this open until the fix makes it to our own packages.

**Comment by nzjrs** [comment]
I also think we should cherry pick
https://github.com/opencv/opencv/commit/a41d877fe6c7229e27d331fcc514150fd836bd73

On 27 May 2017 19:03, "Santi Villalba" <notifications@github.com> wrote:

Apparently the problem was an unfortunate combination of an opencv 3.2.0
issue <https://github.com/opencv/opencv/issues/8097> (fixed in master
<https://github.com/opencv/opencv/pull/8561>), building with an old version
of gcc (the price to pay when you want stuff to work almost anywhere) and
tests that were not running. It probably will get solved when this PR
<https://github.com/conda-forge/opencv-feedstock/pull/75> gets merged
upstream. I keep this open until the fix makes it to our own packages.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/loopbio/opencv-feedstock/issues/6#issuecomment-304464267>,
or mute the thread

**Comment by sdvillal** [comment]
Closing this as it is all fixed with our forthcoming new package.
