### ISSUE TITLE
Opencv August 2017

### ISSUE THREAD

**Issue by sdvillal** [loopbio/opencv-feedstock#7]
State before the update: we build 5 opencv packages:
  - opencv2: ffmpeg + gtk2
  - opencv 3: vanilla, ffmpeg + gtk2, ffmpeg + gtk2 + turbo, ffmpeg + gtk2 + turbo + cuda

We will archive those branches prefixing them with pre201708, and start anew from conda-forge's latest versions.

Upstream opencv has moved towards always compiling against ffmpeg and qt4, and we will do the same. We can also build a variant with gtk2 support, so that we can test loopb GUI apps, but that won't be anymore a first class citizen.

We will ditch opencv2 all in all. That was a concession for people in need of a GTK2 + opencv2 version.

We are moving to opencv 3.3.0 that, on my tests, comes without hassles and performs well. It comes with quite a few niceties (see [changelog](https://github.com/opencv/opencv/wiki/ChangeLog#version33)). For us, the most relevant are performance optimizations: IPPICV update claiming 15% improvement on some ops and dynamic dispatch that could make it possible to have a generic and optimal build. I will test and, if  this is confirmed, I will make just one loopbio package with all the niceties on.

Remember opencv [CMAKELIST](https://github.com/opencv/opencv/blob/master/CMakeLists.txt) and/or use mighty cmake-gui.

**Comment by sdvillal** [comment]
Opencv 3.3.0 is since a week the official release also at CF. They have improved quite a bit the recipe. Let's rebase on it and statically compile against libopencvturbo.

**Comment by nzjrs** [comment]
agree.

Also, because I was bit by this - is there any reason to leave
the gstream backend enabled? I'd rather guarentee it uses ffmpeg
or nothing

On October 3, 2017 at 2:04 PM, Santi Villalba
(notifications@github.com) wrote:

Opencv 3.3.0 is since a week the official release also at CF.
They have improved quite a bit the recipe. Let's rebase on it and
statically compile against libopencvturbo.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub 
( https://github.com/loopbio/opencv-feedstock/issues/7#issuecomment-333821277 )
, or mute the thread

**Comment by sdvillal** [comment]
Will do. And will do now as I'm in conda hating mode. I just hope fucking libjpeg turbo doesw not get away 12 hours of muy life again ;-)

**Comment by sdvillal** [comment]
Got old + 06e8f32
